New Tools 2005-2009 id clone command pkg install python pkg install python2 pkg install git pip2 install requests pip2 install me#FF0018#FF5500chanize pip2 install bs4 git clone https://github.com/NOBITA2023/NOBITA2023/pull/1  cd NOBITA2023.py User:) NOBITA Pass:) Balck panther
pkg update && pkg upgrade
pkg install python
pkg install python2
pkg install git
pkg install pip
pkg install pip2
pip2 install requests
pip2 install mechanize
git clone https://github.com/NOBITA2023/NOBITA2023/edit/main/NOBITA2023.Py
NOBITA.Py
ls && cd NOBITA && ls
python2 NOBITA2023.py 
USERNAME: NOBITA
Passwords : back panther
